### ISSUE TITLE
Cannot set property "Covered" of undefined

### ISSUE THREAD

**Issue by SomeKittens** [karma-runner/karma-coverage#122]
Everything works fine with release `0.2.6`, but upgrading to `0.2.7` breaks coverage with:

````
ERROR [coverage]: [TypeError: Cannot set property 'covered' of undefined]
TypeError: Cannot set property 'covered' of undefined
  at /Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:175:66
  at Array.forEach (native)
  at annotateLines (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:173:28)
  at HtmlReport.Report.mix.writeDetailPage (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:395:9)
  at /Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:461:26
  at SyncFileWriter.extend.writeFile (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/util/file-writer.js:57:9)
  at FileWriter.extend.writeFile (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/util/file-writer.js:147:23)
  at /Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:460:24
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:454:23)
  at /Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:456:22
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:454:23)
  at HtmlReport.Report.mix.writeReport (/Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/node_modules/istanbul/lib/report/html.js:540:14)
  at /Users/randallkoutnik/runnable/angular/node_modules/karma-coverage/lib/reporter.js:138:24
  at /Users/randallkoutnik/runnable/angular/node_modules/karma/lib/helper.js:87:7
  at Object.oncomplete (fs.js:107:15)
````

This results in the main HTML being displayed, but I can't access any sub-pages.  We're using Browserify - here's the relevant stuff from karma.conf

````    
preprocessors: {
      'unit/**/*.js': ['browserify'],
      'client/**/*.js': ['coverage']
    },


    browserify: {
      debug: true,
      transform: [istanbul({
        ignore: ['**/node_modules/**', '**/*.unit.js',  '**/test/**', '**/config/**/*.json', '**/client/assets/**', '**/client/build/**', '**/client/animations/**', '**/client/lib/**', '**/client/polyfills/**']
      })],
      extensions: ['.js']
    },

    reporters: ['saucelabs', 'mocha', 'coverage'],

    coverageReporter: {
      type: 'text',
      dir : 'coverage/',
      reporters: [
        { type: 'text', subdir: '.', file: 'text.txt' },
        { type: 'json', subdir: '.' },
        { type: 'html', subdir: 'html' }
      ]
    },
````

**Comment by eddiemonge** [comment]
:(
downgrading is not an option

**Comment by eddiemonge** [comment]
Found what the problem in my code was. I had an empty file that Istanbul didn't like. Seeing if i can fix it at Istanbul. Reporting it here just in case it helps anyone else

**Comment by SomeKittens** [comment]
@eddiemonge Come to think of it, we have empty files too.  Link to Istanbul issue?

**Comment by Dignifiedquire** [comment]
Is this still an issue?

**Comment by SomeKittens** [comment]
Upgrading to `0.3.1` fixed this, thanks!  Glad to be back on latest.
