### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Tin-Nguyen** [karma-runner/karma-coverage#167]
Chrome 43.0.2357 (Mac OS X 10.10.2): Executed 313 of 324 (skipped 11) SUCCESS (0.515 secs / 0.313 secs)

ERROR [coverage]: [TypeError: Cannot read property 'text' of undefined]
TypeError: Cannot read property 'text' of undefined
    at <removed>/node_modules/istanbul/lib/report/html.js:283:53
    at Array.forEach (native)
    at annotateBranches (<removed>/node_modules/istanbul/lib/report/html.js:250:30)
    at HtmlReport.Report.mix.writeDetailPage (<removed>/node_modules/istanbul/lib/report/html.js:421:9)
    at <removed>/node_modules/istanbul/lib/report/html.js:484:26
    at SyncFileWriter.extend.writeFile (<removed>/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (<removed>/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at <removed>/node_modules/istanbul/lib/report/html.js:483:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (<removed>/node_modules/istanbul/lib/report/html.js:477:23)

**Comment by Dignifiedquire** [comment]
Could you either post a link to the code or supply a minimal example reproducing this please?

**Comment by Tin-Nguyen** [comment]
Hi @Dignifiedquire ,

I think I've provided all things on my post. Because the Unit Test still works well, and the report has been created/updated successfully. However, we got the error in end of progress.

And I just got the issue when I add `babelify` transform into the config. Have you checked with `babelify` yet?

Please let me know if you need to get what information from my case. I will investigate deeper on this issue today.

Regards,
Tin Nguyen

**Comment by Tin-Nguyen** [comment]
is there any updates on this? the issue still be my tests :((

**Comment by Dignifiedquire** [comment]
Sorry I haven't gotten to it yet, will try to take a look later today

**Comment by jljorgenson18** [comment]
+1

**Comment by Tin-Nguyen** [comment]
Hi @Dignifiedquire ,

I removed `babelify`, the report works fine. I really don't know the root cause. Could you help to check?

**Comment by vectart** [comment]
I switched to `cheap-module-source-map` and the issue is gone. Seems like incorrect sourcemap causes the failure while branch annotation.

**Comment by SpenceDiNicolantonio** [comment]
This appears to be an issue with Istanbul and source maps. See https://github.com/karma-runner/karma-coverage/issues/157#issuecomment-129636012.

**Comment by Dignifiedquire** [comment]
Yes this seems to be the same issue as #157

**Comment by icfantv** [comment]
We had this error and I spent yesterday morning fixing.  [Here's a write-up](https://github.com/gotwarlost/istanbul/issues/602#issuecomment-356062165) of what worked for us.
