### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by falsandtru** [karma-runner/karma-coverage#381]
v2.0.1 threw the following error.

```
TypeError: Cannot read property 'start' of undefined
    at /home/travis/build/falsandtru/securemark/node_modules/istanbul-reports/lib/lcovonly/index.js:31:43
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/home/travis/build/falsandtru/securemark/node_modules/istanbul-reports/lib/lcovonly/index.js:29:30)
    at LcovReport.<computed> [as onDetail] (/home/travis/build/falsandtru/securemark/node_modules/istanbul-reports/lib/lcov/index.js:20:23)
    at Visitor.<computed> [as onDetail] (/home/travis/build/falsandtru/securemark/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/travis/build/falsandtru/securemark/node_modules/istanbul-lib-report/lib/tree.js:114:17)
    at /home/travis/build/falsandtru/securemark/node_modules/istanbul-lib-report/lib/tree.js:118:15
    at Array.forEach (<anonymous>)
    at ReportNode.Node.visit (/home/travis/build/falsandtru/securemark/node_modules/istanbul-lib-report/lib/tree.js:117:24)
    at Tree.visit (/home/travis/build/falsandtru/securemark/node_modules/istanbul-lib-report/lib/tree.js:150:20)
    at /home/travis/build/falsandtru/securemark/node_modules/karma-coverage/lib/reporter.js:278:16
    at /home/travis/build/falsandtru/securemark/node_modules/karma/lib/helper.js:148:7
    at callback (/home/travis/build/falsandtru/securemark/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:167:5)
```

https://travis-ci.org/falsandtru/securemark/jobs/574909673#L263

**Comment by johnjbarton** [comment]
That error suggests the data file coverage data is incomplete:
https://github.com/istanbuljs/istanbuljs/blob/025e8af619c2d20a7789b73d81c3c5f30441a129/packages/istanbul-reports/lib/lcovonly/index.js#L33

This isn't something karma-coverage can fix, unless it is a dependency issue.  Try printing the fileCoverage data, maybe before and after the upgrade.
