### ISSUE TITLE
Unable to get coverage working with karma 0.12.1 

### ISSUE THREAD

**Issue by MindCookin** [karma-runner/karma-coverage#70]
Hello

We have an issue that happens with the last version of karma (0.12.1) and karma-coverage (0.2.1): 

[gulp] Using gulpfile /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/gulpfile.js
[gulp] Starting 'test'...
[gulp] Finished 'test' after 3.03 ms
INFO [karma]: Karma v0.12.1 server started at http://localhost:9123/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket dSKtK0fzmd_P7wgcpXOW with id 98803585
PhantomJS 1.9.7 (Mac OS X) ERROR
  TypeError: 'undefined' is not an object (evaluating '__cov_w5iXYxo9oGaxixd5zUvm3A.s['2']')
  at /Users/medianet/Documents/Work/bbva/wizzo_front_experiments/app/js/components/common/contact-picker-service.js:9
[ ... previous line gets repeated for each test  ... ]

PhantomJS 1.9.7 (Mac OS X): Executed 0 of 0 ERROR (0.19 secs / 0 secs)
ERROR [karma]: [TypeError: Cannot call method 'att' of undefined]
TypeError: Cannot call method 'att' of undefined
    at onBrowserComplete (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma-junit-reporter/index.js:50:11)
    at null.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/events.js:15:22)
    at EventEmitter.emit (events.js:117:20)
    at onComplete (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/browser.js:145:13)
    at Socket.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/lib/events.js:15:22)
    at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
    at SocketNamespace.handlePacket (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/Users/medianet/Documents/Work/bbva/wizzo_front_experiments/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:36:10)

Nothing gets prompt to the console neither the coverage folder get created.

We realised about this because we needed to reinstall our project several times during the week. With the previous karma version (0.12.0) worked fine.

We have karma installed locally and not globally. This was because we experiment problems updating plugins globally.

I am not sure if this issue belongs to your plugin or to karma itself, I realised that there are some problems when doing npm list that refer to fsevents and recursive-readdir. I will also report it to them.

Thanks for all the efforts and keep up the good work.

Greetings

Santi

**Comment by Dignifiedquire** [comment]
Please report a new issue if this is still a problem.
